### ISSUE TITLE
Twitter Cardが表示されない

### ISSUE THREAD

**Issue by tkpea** [MeditationDuck/covid19#11]
## 起こっている問題 / The Problem
- Twitterに`https://covid19-iwate.netlify.com/`を投稿した時にTwitterカードが表示されない
- [Card Validator](https://cards-dev.twitter.com/validator)でチェックすると以下のエラー表示
```
ERROR: Fetching the page failed because it's denied by robots.txt.
```
- エラー表示に記載されているrobots.txtを覗くと以下のように設定されている
```
User-agent: *
Disallow: /
```
- Development Modeだからかな？

### Card validatorの結果
![スクリーンショット 2020-03-25 15 54 34](https://user-images.githubusercontent.com/4443492/77520552-b656ab00-6ec4-11ea-931c-874835cbfe12.png)

### Twitter上での表示
![スクリーンショット 2020-03-25 15 58 26](https://user-images.githubusercontent.com/4443492/77520532-b0f96080-6ec4-11ea-8eb9-37471d66cdb6.png)

## 期待する見せ方・挙動 / Expected Behavior
Facebookのようにサムネイルが表示されて欲しい
![スクリーンショット 2020-03-25 16 04 34](https://user-images.githubusercontent.com/4443492/77521087-7cd26f80-6ec5-11ea-9d41-5c0e0a7d5c1c.png)

## 起こっている問題の再現手段 / Steps to Reproduce

1. Twitterに`https://covid19-iwate.netlify.com/`を投稿
2. [Card Validator](https://cards-dev.twitter.com/validator)で`https://covid19-iwate.netlify.com/`を調査

## 動作環境・ブラウザ / Environment
- macOS 
- Chrome

**Comment by suzuryo** [comment]
.github/workflow/develop.yml の30行目
https://github.com/MeditationDuck/covid19/blob/development/.github/workflows/develop.yml#L30

.github/workflow/staging.yml の30行目
https://github.com/MeditationDuck/covid19/blob/development/.github/workflows/staging.yml#L30

で robots.txt を生成しているので、
.github/workflow/deploy.yml
を使って、netlify にデプロイするようになると、治ると思います。

**Comment by MeditationDuck** [comment]
masterブランチにdevelopmentブランチからマージをすればいいのか？といったところまでは調べたのですが、うまくできておりません。。、、、、
