### ISSUE TITLE
現状のヒアリングと課題点洗い出しのミーティング

### ISSUE THREAD

**Issue by suzuryo** [MeditationDuck/covid19#1301]
現状のヒアリングと課題点洗い出しのミーティング

**Comment by suzuryo** [comment]
- [ ] データ更新の全自動化

**Comment by suzuryo** [comment]
- [ ] ワクチン接種が始まったら、何かしら可視化する要素があるか？

**Comment by suzuryo** [comment]
- [ ] renovate の導入

**Comment by furandon-pig** [comment]
- [ ] 開発者向けドキュメントの整備
  - GitHubのWikiを用いるのが良さそう。

**Comment by suzuryo** [comment]
メモ：個別ページの公開が岩手県も盛岡市も、16:30決め打ちになったようだ
