### ISSUE TITLE
入院病床の表示カードにて、予約済み(入院中+入院療養等調整中)のコマに数値が記入されていない

### ISSUE THREAD

**Issue by YO4** [MeditationDuck/covid19#2694]
## 起こっている問題 / The Problem
- 入院病床の表示カードにて、予約済み(入院中+入院療養等調整中)のコマに数値が記入されていない

## スクリーンショット / Screenshot

![Image 0](https://user-images.githubusercontent.com/2260727/152678927-0db9f0db-8c98-49aa-82b5-725ef0e2da45.png)

## 期待する見せ方・挙動 / Expected Behavior
- 入院中のベッド数のコマに数値が表示されているので、入院療養等調整中の最後のコマにも数値が表示されているのを期待します。(モニタの色調整によっては入院療養等調整中の色が空きの白と見分けにくいですが、それも緩和できるかな)

ref https://github.com/MeditationDuck/covid19/commit/7be03c46d797aa9e523a83dfbd754b3a28670fc6

**Comment by suzuryo** [comment]
@YO4 
issue報告 ＆ 確認ありがとうございます。修正してデプロイしました。
