### ISSUE TITLE
data.json の inspections_summary の labels が1年分しか対応していない？

### ISSUE THREAD

**Issue by suzuryo** [MeditationDuck/covid19#444]
## 改善詳細 / Details of Improvement

data.json
```
{
  "inspections_summary": {
    "data": {
      "labels: [
        "2/13",
        "2/14",
        ....
        "8/06"
      ]
    }
  }
}
```

labels の項目が、strftime('%-m/%d') のデータ形式だけど、2021年の2月13日になって、日付が1周したらどうなるの？

東京版では、どんな議論がされてるだろうか？

**Comment by nard-tech** [comment]
@suzuryo これ私も気になってました．向こうの状況確認してみます．

**Comment by suzuryo** [comment]
https://github.com/tokyo-metropolitan-gov/covid19/issues/5750

**Comment by suzuryo** [comment]
data.json の inspections_summary を削除した。

年の繰り越しをテストする

**Comment by suzuryo** [comment]
1月1日の年越しは問題なさそう。
次はデータが1周する2月13日に要確認。
