### ISSUE TITLE
PositiveRateCard(検査の陽性率)の「抗原検査陽性者数」のデータ生成に対応する

### ISSUE THREAD

**Issue by suzuryo** [MeditationDuck/covid19#450]
## 改善詳細 / Details of Improvement

~~岩手県は 抗原検査での陽性者数は発表していないと思うので、PositiveRateCard.vue の PositiveRate.data[i].antigen_positive_count は「不定」というか、常に 0 になるはず。~~

参考
https://www.pref.iwate.jp/_res/projects/default_project/_page_/001/028/231/20200730_02_1.pdf
page.1
> ※１ ＰＣＲ検査と抗原検査の両方を実施した人は、（）内で表示。ＰＣＲ検査件数の内数とする（抗原検査はＰＣＲ検査前に実施し、全て陰性と判定）。
> ※２ 抗原検査欄は、抗原検査のみ実施した件数を計上する。

1. 抗原検査でスクリーニング
2. 抗原検査で陽性が出た人はPCR検査する
3. PCR検査で陽性が出たら陽性確定
4. 抗原検査件数は抗原検査で陰性でPCR検査に進まなかった件数を発表

という数字の発表の仕方をしていると思うので、~~抗原検査 陽性者数 という数字は岩手県は発表していない~~はず。

2020.08.23 抗原検査で陽性＆PCR検査なしで陽性者確定パターンが発生した

**Comment by nard-tech** [comment]
@suzuryo なるほど．こちらも対応します．

**Comment by suzuryo** [comment]
データ側は

```
"antigen_positive_count": null
```

になるようにしておきました。

https://github.com/suzuryo/covid19-iwate/blob/8a061fae7b2d1a0a1de8bc537dec27d27e294ad6/data_tools/google_sheets_to_data_json/generate_data_json.rb#L402

**Comment by suzuryo** [comment]
8月23日の検査結果で、
抗原検査で陽性、PCR検査なしで陽性者確定のパターンが発生した。

<img width="967" alt="Screen Shot 2020-08-24 at 12 39 27 PM" src="https://user-images.githubusercontent.com/242669/91002437-a7a62880-e609-11ea-9fed-775857370133.png">

- [ ] Google Sheets の修正
- [ ] 生成スクリプトの修正

**Comment by suzuryo** [comment]
抗原検査陽性者数に対応したのでクローズ。

<img width="506" alt="Screen Shot 2020-08-24 at 11 59 13 PM" src="https://user-images.githubusercontent.com/242669/91060919-81fb3c80-e666-11ea-9d22-e026190d1bbf.png">

例 : 2020/08/23
