### ISSUE TITLE
東京の本家リポジトリに岩手版のURLを追加

### ISSUE THREAD

**Issue by suzuryo** [MeditationDuck/covid19#5]
## 改善詳細 / Details of Improvement
- FORKED_SITES.md に岩手版を追加

追加するのは

```
[](03)岩手県|https://covid19-iwate.netlify.com/|有志|[MeditationDuck/covid19](https://github.com/MeditationDuck/covid19)|
```

でいいですか？

**Comment by suzuryo** [comment]
本家のリポジトリにプルリク送っておきました

https://github.com/tokyo-metropolitan-gov/covid19/pull/2287

**Comment by MeditationDuck** [comment]
OKです！ありがとうございます！

**Comment by suzuryo** [comment]
マージされました。

ちなみに

https://github.com/tokyo-metropolitan-gov/covid19/pull/2287#pullrequestreview-381077822
> お疲れさまでした！ stopcovid19.jp のサブドメインは必要ないですか？

というオファーをもらっていますが、どうしましょう？

**Comment by suzuryo** [comment]
マージされたのでクローズします
