### ISSUE TITLE
岩手版の googleAnalytics:id を設定する

### ISSUE THREAD

**Issue by suzuryo** [MeditationDuck/covid19#6]
## 起こっている問題 / The Problem
- nuxt.config.ts の googleAnalytics:id が 東京版になっているので、岩手版に変更する

```
  googleAnalytics: {
    id: 'UA-159417676-1'
  },
```

を変更する必要がある。

@MeditationDuck さんが GoogleAnalytics のアカウントを作成しますか？

**Comment by MeditationDuck** [comment]
作成しておきます。

**Comment by MeditationDuck** [comment]
作成したIDを設定しておきました。

**Comment by MeditationDuck** [comment]
作成し動作確認ができました
