### ISSUE TITLE
東京都版の最新のコードを merge する

### ISSUE THREAD

**Issue by nard-tech** [MeditationDuck/covid19#7]
## 改善詳細 / Details of Improvement
- 東京都版の最新のコードを merge する
    - ドキュメント類を最新のものに合わせたい
    - その他のコードも最新のものに追従したい

**Comment by nard-tech** [comment]
@MeditationDuck reopen になってますけど，何かありましたか？

**Comment by MeditationDuck** [comment]
いえなにもないです。あれ？履歴を残したほうが良さそうとのことだったのでやりました。使い方がよくわかってないです。すいません

**Comment by nard-tech** [comment]
@MeditationDuck PR はもう merge しましたよね？であればこの issue は用済みなので close してください．close したから見れなくなるということはないので．履歴はしっかり残ります．

**Comment by MeditationDuck** [comment]
了解です！何度もすいません　ありがとうございます！
