### ISSUE TITLE
東京都のオープンデータサイトへのリンクが表示されている

### ISSUE THREAD

**Issue by nard-tech** [MeditationDuck/covid19#9]
## 起こっている問題 / The Problem
- 「【帰国者・接触者相談センター】受付 相談件数」「（一般相談）受付への相談件数」に東京都のオープンデータサイトへのリンクが表示されている

## スクリーンショット / Screenshot
<img width="547" alt="スクリーンショット 2020-03-25 18 05 06" src="https://user-images.githubusercontent.com/23148331/77519673-3ed44c00-6ec3-11ea-9e83-d45b6ff972ab.png">
<img width="550" alt="スクリーンショット 2020-03-25 18 05 24" src="https://user-images.githubusercontent.com/23148331/77519677-4136a600-6ec3-11ea-9f15-03acd89507ff.png">

## 期待する見せ方・挙動 / Expected Behavior
- オープンデータサイトへのリンクを表示しない

## 起こっている問題の再現手段 / Steps to Reproduce
https://covid19-iwate.netlify.com/ を開く

## 動作環境・ブラウザ / Environment
- macOS, Chrome

**Comment by nard-tech** [comment]
着手します

**Comment by nard-tech** [comment]
@MeditationDuck reopen になってますけど，何かありましたか？

**Comment by nard-tech** [comment]
@MeditationDuck #7 と同様，こちらも close して問題ないと思いますよ

**Comment by MeditationDuck** [comment]
ありがとうございます！
